language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=dev-master

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text
